name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run Cypress Tests 🧪
        uses: cypress-io/github-action@v5
        with:
          start: "npm run dev"

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
          if-no-files-found: ignore
